apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-frontend
  name: udaconnect-frontend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30006
  selector:
    service: udaconnect-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-frontend
  name: udaconnect-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-frontend
  template:
    metadata:
      labels:
        service: udaconnect-frontend
    spec:
      containers:
      - image: khalilelf441/udaconnect-frontend:latest
        name: udaconnect-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
        env:
        - name: REACT_APP_CONNECTION_SERVICE
          value: udaconnect-connectionservice:5003
        - name: REACT_APP_PERSON_SERVICE
          value: udaconnect-personservice:5001
      restartPolicy: Always
