apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connectionservice
  name: udaconnect-connectionservice
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 5003
    nodePort: 30003
  selector:
    service: udaconnect-connectionservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connectionservice
  name: udaconnect-connectionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connectionservice
  template:
    metadata:
      labels:
        service: udaconnect-connectionservice
    spec:
      containers:
      - image: khalilelf441/udaconnect-connectionservice:latest
        name: udaconnect-connectionservice
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: LOCATION_ENDPOINT_PORT
          value: "5002"
        - name: LOCATION_SERVICE
          value: udaconnect-locationservice
        - name: GRPC_SERVER
          value: udaconnect-personservice:5005
      restartPolicy: Always
