name: Udaconnect - Package Services with Docker

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ feature/dockerize-m-services ]

#  ./modules/ConnectionService/Dockerfile
#  ./modules/frontend/Dockerfile
#  ./modules/LocationProcessor/Dockerfile
#  ./modules/LocationService/Dockerfile
#  ./modules/PersonService/Dockerfile


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: uda_env
    env:
      DOCKERHUB_REPOSITORY: khalilelf441
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./modules/ConnectionService/Dockerfile
            image: uda-connectionservice
          - dockerfile: ./modules/frontend/Dockerfile
            image: uda-frontend
          - dockerfile: ./modules/LocationProcessor/Dockerfile
            image: uda-locationprocessor
          - dockerfile: ./modules/LocationService/Dockerfile
            image: uda-locationservice
          - dockerfile: ./modules/PersonService/Dockerfile
            image: uda-personservice
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKERHUB_REPOSITORY }}/${{ matrix.image }}:latest, ${{ env.DOCKERHUB_REPOSITORY }}/${{ matrix.image }}:${{ format('v1.0.{0}', github.run_number) }}